In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

## Working with Dates

In [6]:
# Converting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [9]:
date['date_year'] = date['date'].dt.year
date['date_month_no'] = date['date'].dt.month
date['date_month_name'] = date['date'].dt.month_name()
date['date_day'] = date['date'].dt.day

# day of week
date['date_dow'] = date['date'].dt.dayofweek

# day of week - name
date['date_dow_name'] = date['date'].dt.day_name()

# is weekend?
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

# Extract Quarter
date['quarter'] = date['date'].dt.quarter

#Extract Semester
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

In [10]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

In [11]:
# Extract Time elapsed between dates
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 9, 18, 16, 19, 29, 911982)

In [12]:
today - date['date']

0     2474 days 16:19:29.911982
1     2956 days 16:19:29.911982
2     2887 days 16:19:29.911982
3     2589 days 16:19:29.911982
4     2812 days 16:19:29.911982
                 ...
995   2902 days 16:19:29.911982
996   2843 days 16:19:29.911982
997   2691 days 16:19:29.911982
998   2756 days 16:19:29.911982
999   2530 days 16:19:29.911982
Name: date, Length: 1000, dtype: timedelta64[ns]

In [13]:
(today - date['date']).dt.days

0      2474
1      2956
2      2887
3      2589
4      2812
       ...
995    2902
996    2843
997    2691
998    2756
999    2530
Name: date, Length: 1000, dtype: int64

## Working with Dates

In [18]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [19]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [20]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [21]:
#Extract Time part
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [22]:
#Time difference
today - time['date']

0     4660 days 15:29:29.911982
1     4524 days 16:39:29.911982
2     5010 days 15:58:29.911982
3     4312 days 15:48:29.911982
4     4709 days 17:08:29.911982
                 ...
995   5299 days 15:29:29.911982
996   4620 days 17:05:29.911982
997   5085 days 16:42:29.911982
998   5201 days 16:45:29.911982
999   4473 days 16:54:29.911982
Name: date, Length: 1000, dtype: timedelta64[ns]

In [23]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      111855.491642
1      108592.658309
2      120255.974976
3      103503.808309
4      113033.141642
           ...
995    127191.491642
996    110897.091642
997    122056.708309
998    124840.758309
999    107368.908309
Name: date, Length: 1000, dtype: float64

In [24]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.711329e+06
1      6.515559e+06
2      7.215358e+06
3      6.210228e+06
4      6.781988e+06
           ...
995    7.631489e+06
996    6.653825e+06
997    7.323402e+06
998    7.490445e+06
999    6.442134e+06
Name: date, Length: 1000, dtype: float64

In [25]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      4.026798e+08
1      3.909336e+08
2      4.329215e+08
3      3.726137e+08
4      4.069193e+08
           ...
995    4.578894e+08
996    3.992295e+08
997    4.394041e+08
998    4.494267e+08
999    3.865281e+08
Name: date, Length: 1000, dtype: float64